use crm;

CREATE TABLE `customer` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
	`PASSWORD` VARCHAR(200) NOT NULL COMMENT '密码',
	`MOBILE` VARCHAR(15) NULL DEFAULT NULL COMMENT '联系手机号',
	`IDENTIFICATION` VARCHAR(20) NULL DEFAULT NULL COMMENT '身份证号',
	`EMAIL` VARCHAR(50) NOT NULL COMMENT '邮箱',
	`IS_EMAIL_VERIFY` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否邮箱验证(0：否，1：是)',
	`IS_FROZEN` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否冻结（0：否，1：是）',
	`IS_ENABLE` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否失效（0：否，1：是）',
	`CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`UPDATE_TIME` DATETIME NULL DEFAULT NULL COMMENT '修改时间',
	PRIMARY KEY (`ID`),
	INDEX `AK_unique_username` (`USERNAME`),
	INDEX `AK_unique_email` (`EMAIL`)
)
COMMENT='客户表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;