create database pns;

use pns;

CREATE TABLE `orders` (
	`TIMESTAMP` BIGINT(20) NOT NULL,
	`OID` VARCHAR(45) NULL DEFAULT NULL,
	`CID` BIGINT(20) NULL DEFAULT NULL,
	`TYPE` VARCHAR(45) NULL DEFAULT NULL,
	`SIDE` VARCHAR(45) NULL DEFAULT NULL,
	`PNSOID` VARCHAR(45) NULL DEFAULT NULL,
	`POID` VARCHAR(45) NULL DEFAULT NULL,
	`PNSID` BIGINT(20) NULL DEFAULT NULL,
	`PNSGID` BIGINT(20) NULL DEFAULT NULL,
	`PRICE` BIGINT(20) NULL DEFAULT NULL,
	`QUANT` BIGINT(20) NULL DEFAULT NULL,
	`FORM` VARCHAR(45) NULL DEFAULT NULL,
	`STATUS` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`TIMESTAMP`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;


CREATE TABLE `pns` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`TIME` BIGINT(20) NULL DEFAULT NULL,
	`OID` VARCHAR(45) NULL DEFAULT NULL,
	`PNSID` BIGINT(20) NOT NULL,
	`PNSGID` BIGINT(20) NULL DEFAULT NULL,
	`POID` BIGINT(20) NOT NULL COMMENT 'product owner\'s id \\nnormally client',
	`SIDE` VARCHAR(45) NOT NULL,
	`PRICE` BIGINT(20) NULL DEFAULT NULL,
	`QUANT` BIGINT(20) NOT NULL DEFAULT '0',
	`TOTAL` BIGINT(20) NULL DEFAULT NULL,
	`STATUS` VARCHAR(45) NULL DEFAULT NULL,
	`TRADED` BIGINT(20) NOT NULL DEFAULT '0',
	`MARGIN` BIGINT(20) NOT NULL DEFAULT '0',
	`NET` BIGINT(20) NOT NULL DEFAULT '0',
	`MAX` BIGINT(20) NOT NULL DEFAULT '0',
	`MIN` BIGINT(20) NOT NULL DEFAULT '0',
	`CAN` BIGINT(20) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `OID_UNIQUE` (`OID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=31;


CREATE TABLE `requests` (
	`RID` VARCHAR(45) NOT NULL COLLATE 'latin1_swedish_ci',
	`timestamp` VARCHAR(45) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`CID` VARCHAR(45) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`TTYPE` VARCHAR(45) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`RBODY` VARCHAR(45) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`RID`),
	UNIQUE INDEX `RID_UNIQUE` (`RID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;