use crm;

CREATE TABLE `cacc` (
	`CID` BIGINT(20) NOT NULL,
	`CGID` BIGINT(20) NOT NULL,
	`PNSGID` BIGINT(20) NOT NULL,
	`PNSID` BIGINT(20) NOT NULL,
	`BALANCE` BIGINT(20) NULL DEFAULT '0',
	`MARGIN` BIGINT(20) NULL DEFAULT '0',
	`FREEMARGIN` BIGINT(20) NULL DEFAULT '0',
	`PREBALAN` BIGINT(20) NULL DEFAULT '0',
	`CHANGEBALAN` BIGINT(20) NULL DEFAULT '0',
	`PNL` BIGINT(20) NULL DEFAULT '0',
	PRIMARY KEY (`CID`, `PNSGID`, `PNSID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;


CREATE TABLE `manager` (
	`managerid` INT(11) NOT NULL AUTO_INCREMENT,
	`loginname` VARCHAR(45) NULL DEFAULT NULL,
	`password` VARCHAR(45) NULL DEFAULT NULL,
	`email` VARCHAR(45) NULL DEFAULT NULL,
	`privillege` VARCHAR(45) NULL DEFAULT NULL,
	PRIMARY KEY (`managerid`),
	UNIQUE INDEX `managerid_UNIQUE` (`managerid`),
	UNIQUE INDEX `loginname_UNIQUE` (`loginname`),
	UNIQUE INDEX `email_UNIQUE` (`email`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=3;
INSERT INTO `manager` (`managerid`, `loginname`, `password`, `email`, `privillege`) VALUES (1, 'derek', '123', 'hello@163.com', '0');
INSERT INTO `manager` (`managerid`, `loginname`, `password`, `email`, `privillege`) VALUES (2, 'jack', '1234', 'jack@163.com', '0');

CREATE TABLE `permission` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`USER_ID` INT(11) NOT NULL COMMENT '用户id',
	`PERMISSION_CODE` BIGINT(20) NOT NULL COMMENT '用户权限码',
	`SCAN_ALL_CUSTOMERS` INT(1) NOT NULL DEFAULT '0' COMMENT '查看所有用户',
	`SCAN_CUSTOMER_POSITION` INT(1) NOT NULL DEFAULT '0' COMMENT '查看客户仓位',
	`CREATE_CUSTOMER` INT(1) NOT NULL DEFAULT '0' COMMENT '增加客户',
	`UPDATE_CUSTOMER` INT(1) NOT NULL DEFAULT '0' COMMENT '修改客户信息',
	`LIMIT_CUSTOMER_TRADE` INT(1) NOT NULL DEFAULT '0' COMMENT '限制用户交易   ',
	`LIMIT_CUSTOMER_DEPOSIT_WITHDRAW` INT(1) NOT NULL DEFAULT '0' COMMENT '限制用户出入金 ',
	`UPDATE_CUSTOMER_ORDERS` INT(1) NOT NULL DEFAULT '0' COMMENT '修改客户订单',
	`CREATE_ORDER` INT(1) NOT NULL DEFAULT '0' COMMENT '新增订单',
	`DELETE_ORDER` INT(1) NOT NULL DEFAULT '0' COMMENT '删除订单',
	`SCAN_OPRATOR_LOG` INT(1) NOT NULL DEFAULT '0' COMMENT '查看操作日志  ',
	`MANAGE_USER` INT(1) NOT NULL DEFAULT '0' COMMENT '管理登录用户',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `AK_userId` (`USER_ID`)
)
COMMENT='权限表'
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=3;
INSERT INTO `permission` (`ID`, `USER_ID`, `PERMISSION_CODE`, `SCAN_ALL_CUSTOMERS`, `SCAN_CUSTOMER_POSITION`, `CREATE_CUSTOMER`, `UPDATE_CUSTOMER`, `LIMIT_CUSTOMER_TRADE`, `LIMIT_CUSTOMER_DEPOSIT_WITHDRAW`, `UPDATE_CUSTOMER_ORDERS`, `CREATE_ORDER`, `DELETE_ORDER`, `SCAN_OPRATOR_LOG`, `MANAGE_USER`) VALUES (1, 1, 2047, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO `permission` (`ID`, `USER_ID`, `PERMISSION_CODE`, `SCAN_ALL_CUSTOMERS`, `SCAN_CUSTOMER_POSITION`, `CREATE_CUSTOMER`, `UPDATE_CUSTOMER`, `LIMIT_CUSTOMER_TRADE`, `LIMIT_CUSTOMER_DEPOSIT_WITHDRAW`, `UPDATE_CUSTOMER_ORDERS`, `CREATE_ORDER`, `DELETE_ORDER`, `SCAN_OPRATOR_LOG`, `MANAGE_USER`) VALUES (2, 2, 1022, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0);
